CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(200),
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150),
    status VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    created_at DATE DEFAULT SYSDATE
);
CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(200)
);
CREATE TABLE environments (
    environment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    environment_name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(200),
    status VARCHAR2(20) DEFAULT 'Active'
);
CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_ur_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_ur_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
);
CREATE TABLE change_requests (
    request_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_number VARCHAR2(30) NOT NULL UNIQUE,

    title VARCHAR2(200) NOT NULL,
    description CLOB NOT NULL,
    reason CLOB NOT NULL,

    change_type VARCHAR2(20) NOT NULL,
    priority VARCHAR2(20) NOT NULL,
    risk_level VARCHAR2(20) NOT NULL,

    affected_database VARCHAR2(100),
    affected_object VARCHAR2(200),

    environment_id NUMBER,

    proposed_implementation_date DATE,

    rollback_plan CLOB,

    status VARCHAR2(30) DEFAULT 'Draft' NOT NULL,

    requester_id NUMBER NOT NULL,

    created_at DATE DEFAULT SYSDATE,
    updated_at DATE,

    CONSTRAINT fk_cr_requester
        FOREIGN KEY (requester_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_cr_environment
        FOREIGN KEY (environment_id)
        REFERENCES environments(environment_id)
);
CREATE TABLE change_scripts (
    script_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_id NUMBER NOT NULL,

    script_name VARCHAR2(200),
    script_content CLOB NOT NULL,

    script_type VARCHAR2(30),
    execution_order NUMBER,

    created_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_script_request
        FOREIGN KEY (request_id)
        REFERENCES change_requests(request_id)
);
CREATE TABLE change_reviews (
    review_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_id NUMBER NOT NULL,
    reviewer_id NUMBER NOT NULL,

    review_status VARCHAR2(20) NOT NULL,
    comments CLOB,

    reviewed_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_review_request
        FOREIGN KEY (request_id)
        REFERENCES change_requests(request_id),

    CONSTRAINT fk_review_reviewer
        FOREIGN KEY (reviewer_id)
        REFERENCES users(user_id)
);
CREATE TABLE change_approvals (
    approval_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_id NUMBER NOT NULL,
    approver_id NUMBER NOT NULL,

    approval_level NUMBER NOT NULL,

    decision VARCHAR2(20) NOT NULL,
    comments CLOB,

    decision_date DATE DEFAULT SYSDATE,

    CONSTRAINT fk_approval_request
        FOREIGN KEY (request_id)
        REFERENCES change_requests(request_id),

    CONSTRAINT fk_approval_approver
        FOREIGN KEY (approver_id)
        REFERENCES users(user_id)
);
CREATE TABLE test_results (
    test_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_id NUMBER NOT NULL,
    tester_id NUMBER NOT NULL,

    test_type VARCHAR2(30),
    test_status VARCHAR2(20),

    validation_result CLOB,
    errors CLOB,
    warnings CLOB,
    test_evidence CLOB,

    tested_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_test_request
        FOREIGN KEY (request_id)
        REFERENCES change_requests(request_id),

    CONSTRAINT fk_test_tester
        FOREIGN KEY (tester_id)
        REFERENCES users(user_id)
);
CREATE TABLE deployments (
    deployment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_id NUMBER NOT NULL,
    script_id NUMBER,

    deployed_by NUMBER NOT NULL,
    environment_id NUMBER NOT NULL,

    deployment_status VARCHAR2(30) NOT NULL,

    started_at DATE,
    completed_at DATE,

    execution_output CLOB,
    error_message CLOB,

    CONSTRAINT fk_deploy_request
        FOREIGN KEY (request_id)
        REFERENCES change_requests(request_id),

    CONSTRAINT fk_deploy_script
        FOREIGN KEY (script_id)
        REFERENCES change_scripts(script_id),

    CONSTRAINT fk_deploy_user
        FOREIGN KEY (deployed_by)
        REFERENCES users(user_id),

    CONSTRAINT fk_deploy_environment
        FOREIGN KEY (environment_id)
        REFERENCES environments(environment_id)
);
CREATE TABLE rollbacks (
    rollback_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    deployment_id NUMBER NOT NULL,
    rollback_script_id NUMBER,

    executed_by NUMBER NOT NULL,

    rollback_status VARCHAR2(30),

    started_at DATE,
    completed_at DATE,

    execution_output CLOB,
    error_message CLOB,

    reason CLOB,

    CONSTRAINT fk_rollback_deployment
        FOREIGN KEY (deployment_id)
        REFERENCES deployments(deployment_id),

    CONSTRAINT fk_rollback_script
        FOREIGN KEY (rollback_script_id)
        REFERENCES change_scripts(script_id),

    CONSTRAINT fk_rollback_user
        FOREIGN KEY (executed_by)
        REFERENCES users(user_id)
);
CREATE TABLE change_history (
    history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    request_id NUMBER NOT NULL,
    changed_by NUMBER,

    old_status VARCHAR2(30),
    new_status VARCHAR2(30),

    comments CLOB,

    changed_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_history_request
        FOREIGN KEY (request_id)
        REFERENCES change_requests(request_id),

    CONSTRAINT fk_history_user
        FOREIGN KEY (changed_by)
        REFERENCES users(user_id)
);
CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    user_id NUMBER,

    action_type VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50),
    entity_id NUMBER,

    action_details CLOB,

    ip_address VARCHAR2(50),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);
